from enum import StrEnum


class ScanSource(StrEnum):
    """Supported sources of images or files to scan."""
    VISITING_CARD = "Visiting Card"
    BUSINESS_CARD = "Business Card"
    A4_DOCUMENTS = "A4 Documents"
    FORMS = "Forms"
    FLYERS = "Flyers"
    POSTERS = "Posters"
    SHOP_BOARDS = "Shop Boards"
    ROAD_BANNERS = "Road Banners"
    BILLBOARDS = "Billboards"
    RESTAURANT_MENUS = "Restaurant Menus"
    LAPTOP_SCREEN = "Laptop Screen"
    MOBILE_SCREEN = "Mobile Screen"
    GALLERY_IMAGES = "Gallery Images"
    CAMERA = "Camera"
    SCREENSHOT = "Screenshot"
    PDF = "PDF"


class ScanJobStatus(StrEnum):
    """Tracking lifecycle status for a ScanJob."""
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class LogoStatus(StrEnum):
    """Detection status of a company logo in the scanned image."""
    DETECTED = "DETECTED"
    DEFAULT = "DEFAULT"
    NONE = "NONE"


class ReviewStatus(StrEnum):
    """Manual review outcomes for overall ScanResult."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class FieldReviewStatus(StrEnum):
    """Detailed manual action history applied to a single detected field."""
    UNREVIEWED = "UNREVIEWED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EDITED = "EDITED"
    MERGED = "MERGED"
    SPLIT = "SPLIT"
    RENAMED = "RENAMED"


class DetectedFieldType(StrEnum):
    """Granular field types extracted from scanned sources."""
    PERSON_NAME = "Person Name"
    COMPANY_NAME = "Company Name"
    BUSINESS_NAME = "Business Name"
    PHONE = "Phone"
    MOBILE = "Mobile"
    EMAIL = "Email"
    WEBSITE = "Website"
    ADDRESS = "Address"
    GST = "GST"
    PIN = "PIN"
    CITY = "City"
    STATE = "State"
    COUNTRY = "Country"
    DESIGNATION = "Designation"
    DEPARTMENT = "Department"
    SOCIAL_MEDIA = "Social Media"
    OPENING_HOURS = "Opening Hours"
    BUSINESS_CATEGORY = "Business Category"
    CUSTOM = "Custom Fields"


class AISuggestionType(StrEnum):
    """Extracted semantic metadata suggestions generated by AI analysis."""
    DOCUMENT_TYPE = "Document Type"
    BUSINESS_CATEGORY = "Business Category"
    DETECTED_LANGUAGE = "Detected Language"
    KEYWORDS = "Keywords"
    POSSIBLE_COMPANY = "Possible Company"
    POSSIBLE_CONTACT = "Possible Contact"
    POSSIBLE_DUPLICATE = "Possible Duplicate"
    POSSIBLE_WEBSITE = "Possible Website"
    POSSIBLE_SOCIAL_LINKS = "Possible Social Links"
