apiVersion: v1
kind: Service
metadata:
  name: leadscan-api-service
  namespace: leadscan
spec:
  type: ClusterIP
  selector:
    app: leadscan-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
